#Numpy Array operation

In [4]:
import numpy as np

arr=np.arange(1,11)
print("Array is ",arr)
print("Basic slicing ",arr[2:7])

print("Basic slicing ",arr[1:8:2])
print("Negative indexing ",arr[-3])

Array is  [ 1  2  3  4  5  6  7  8  9 10]
Basic slicing  [3 4 5 6 7]
Basic slicing  [2 4 6 8]
Negative indexing  8


In [7]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print("specific element ",arr_2d[1,2])
print("Entire row ",arr_2d[1])
print("Entire coulmn ",arr_2d[:, 1]) #this is foe whole column (: ->target all the rows and we want values of first row)



specific element  6
Entire row  [4 5 6]
Entire coulmn  [2 5 8]


In [12]:
#SORTING 

unsorted=np.array([3,1,4,1,5,9,2,6])
print("Sorted array ",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d array by column  ",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2d array by column  ",np.sort(arr_2d_unsorted,axis=1))



Sorted array  [1 1 2 3 4 5 6 9]
Sorted 2d array by column   [[1 1]
 [2 2]
 [3 3]]
Sorted 2d array by row   [[1 3]
 [1 2]
 [2 3]]
Sorted 2d array by row   [[1 3]
 [1 2]
 [2 3]]


In [14]:
#Filter 

numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers%2==0]
print("even_numbers ",even_number)

even_numbers  [ 2  4  6  8 10]


In [17]:
#FIlter with mask

mask=numbers>5
even=numbers%2==0
print("Numbers grater than 5",numbers[mask])
print("Numbers even ",numbers[even])


Numbers grater than 5 [ 6  7  8  9 10]
Numbers even  [ 2  4  6  8 10]


In [28]:
##Fancy indexing and np.where()
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print("NP where ",numbers[where_result])

condition_array=np.where(numbers>5,numbers*4,numbers)
print(condition_array)

[1 3 5]
NP where  [ 6  7  8  9 10]
[ 1  2  3  4  5 24 28 32 36 40]


In [30]:
#adding or removing data 

arr1=np.array([1,2,3])
arr2=np.array([4,2,6])

combined=np.concatenate((arr1,arr2))
print("concatenate arr1+arr2",combined )

concatenate arr1+arr2 [1 2 3 4 2 6]


In [33]:
#array comaptibilty

a=np.array([1,2,3])
b=np.array([4,5,6,7])
c=np.array([7,8,9])

print("Compatibility shapes",a.shape==b.shape)
print("Compatibility shapes",a.shape==c.shape)

Compatibility shapes False
Compatibility shapes True


In [39]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

with_new_row=np.vstack((original,new_row)) #add new row 

print(original)
print("\n")
print(with_new_row)
print("\n")
new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print("Original : ",original)
print("With new column ",with_new_col)


[[1 2]
 [3 4]]


[[1 2]
 [3 4]
 [5 6]]


Original :  [[1 2]
 [3 4]]
With new column  [[1 2 7]
 [3 4 8]]


In [40]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print(deleted)

[1 2 4 5]
