In [9]:
import numpy as np
arr_1d=np.array([1,2,3,4,5])
print("1D array" ,arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])

print("2 D array",arr_2d)

1D array [1 2 3 4 5]
2 D array [[1 2 3]
 [4 5 6]]


In [26]:
import time
py_list=[1,2,3]
# x=0
# for i in py_list:
#     py_list[x]=i*2
#     x=x+1
    
# print("Python list multiplication ",py_list)

print("Python list multiplication ",py_list*2)
#so np.array help us to multiply element wise 


np_array=np.array([1,2,3])
print("numpy array multiplication ",np_array*2)
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n list operation time  ",time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2 
print("\n numpy oeration time  ",time.time()-start)



Python list multiplication  [1, 2, 3, 1, 2, 3]
numpy array multiplication  [2 4 6]

 list oeration time   0.10280585289001465
[      0       2       4 ... 1999994 1999996 1999998]

 numpy oeration time   0.006921291351318359


In [35]:
#Creating array from scratch 
zeros=np.zeros((3,4))
print(zeros)
print("\n ones array")
ones=np.ones((2,3))
print(ones)


full=np.full((2,2),7)
print("\nFull array is :-",full)

rand=np.random.random((2,3))
print("\n rand array is :-",rand)

sequence=np.arange(0,9)
print("\n sequence array is :-",sequence)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 ones array
[[1. 1. 1.]
 [1. 1. 1.]]

Full array is :- [[7 7]
 [7 7]]

 rand array is :- [[0.61870406 0.37816507 0.64361154]
 [0.84252159 0.87733212 0.89306822]]

 sequence array is :- [0 1 2 3 4 5 6 7 8]


In [41]:
#Vector ,matrix and tensor
vector=np.array([1,2,3])
# print(f"Vector is {vector}") 
print("Vector is ",vector)

Matrix=np.array([[1,2,3],[4,5,6]])
print("\nMatrix is ",Matrix)

Tensor=np.array([[[1,2],[3,4]],
                [[5,6],[7,8]]])
print(Tensor)

Vector is  [1 2 3]

Matrix is  [[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


###Array reshaping 

In [50]:
import numpy as np

arr = np.arange(12)
print("original output:", arr)

reshaped = arr.reshape((3, 4))  
print("reshaped output:\n", reshaped)

flattend=reshaped.flatten()
print("\nFlattened array is ",flattend)

ravel=reshaped.ravel()
print("\n raveled :",ravel)

# ravel return view(original array ) instead of copy


original output: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped output:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array is  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled : [ 0  1  2  3  4  5  6  7  8  9 10 11]
